### PR TITLE
Fix #115 Concurrency issue when adding documents.

### LINKED ISSUE #115: DailyIndex.EnsureDateIndexAsync: InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state.
Came across this in our logs

```
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Foundatio.Repositories.Elasticsearch.Configuration.DailyIndex.EnsureDateIndexAsync(DateTime utcDate) in /_/src/Foundatio.Repositories.Elasticsearch/Configuration/DailyIndex.cs:line 150
   at Foundatio.Repositories.Elasticsearch.ElasticRepositoryBase`1.IndexDocumentsAsync(IReadOnlyCollection`1 documents, Boolean isCreateOperation, ICommandOptions options) in /_/src/Foundatio.Repositories.Elasticsearch/Repositories/ElasticRepositoryBase.cs:line 1252
   at Foundatio.Repositories.Elasticsearch.ElasticRepositoryBase`1.AddAsync(IEnumerable`1 documents, ICommandOptions options) in /_/src/Foundatio.Repositories.Elasticsearch/Repositories/ElasticRepositoryBase.cs:line 93
   at Foundatio.Repositories.Elasticsearch.ElasticRepositoryBase`1.AddAsync(T document, ICommandOptions options) in /_/src/Foundatio.Repositories.Elasticsearch/Repositories/ElasticRepositoryBase.cs:line 67
```

### PR DESCRIPTION
**Pull request by niemyjski**
Fixes #115 

```
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Foundatio.Repositories.Elasticsearch.Configuration.DailyIndex.EnsureDateIndexAsync(DateTime utcDate) in /_/src/Foundatio.Repositories.Elasticsearch/Configuration/DailyIndex.cs:line 150
   at Foundatio.Repositories.Elasticsearch.ElasticRepositoryBase`1.IndexDocumentsAsync(IReadOnlyCollection`1 documents, Boolean isCreateOperation, ICommandOptions options) in /_/src/Foundatio.Repositories.Elasticsearch/Repositories/ElasticRepositoryBase.cs:line 1252
   at Foundatio.Repositories.Elasticsearch.ElasticRepositoryBase`1.AddAsync(IEnumerable`1 documents, ICommandOptions options) in /_/src/Foundatio.Repositories.Elasticsearch/Repositories/ElasticRepositoryBase.cs:line 93
   at Foundatio.Repositories.Elasticsearch.ElasticRepositoryBase`1.AddAsync(T document, ICommandOptions options) in /_/src/Foundatio.Repositories.Elasticsearch/Repositories/ElasticRepositoryBase.cs:line 67
```

### CODE REVIEW

File: src/Foundatio.Repositories.Elasticsearch/Configuration/DailyIndex.cs [hunk 1]
```diff
@@ -131,9 +135,12 @@ protected override DateTime GetIndexDate(string index)
         return DateTime.MaxValue;
     }
 
-    private readonly Dictionary<DateTime, object> _ensuredDates = new();
     protected async Task EnsureDateIndexAsync(DateTime utcDate)
     {
+        await using var indexLock = await _ensureIndexLock.AcquireAsync($"Index:{Name}", TimeSpan.FromMinutes(1)).AnyContext();
```
Comment (niemyjski) [inline src/Foundatio.Repositories.Elasticsearch/Configuration/DailyIndex.cs:140]: Not in love with this lock name but it works.

File: src/Foundatio.Repositories.Elasticsearch/Configuration/DailyIndex.cs [hunk 2]
```diff
@@ -131,9 +135,12 @@ protected override DateTime GetIndexDate(string index)
         return DateTime.MaxValue;
     }
 
-    private readonly Dictionary<DateTime, object> _ensuredDates = new();
     protected async Task EnsureDateIndexAsync(DateTime utcDate)
     {
+        await using var indexLock = await _ensureIndexLock.AcquireAsync($"Index:{GetVersionedIndex(utcDate.Date)}", TimeSpan.FromMinutes(1)).AnyContext();
```
Comment (niemyjski) [inline src/Foundatio.Repositories.Elasticsearch/Configuration/DailyIndex.cs:140]: not in love that some date logic and this index name gets created after this, but felt like this needed to happen like this for the lock

File: src/Foundatio.Repositories.Elasticsearch/Configuration/DailyIndex.cs [hunk 3]
```diff
@@ -131,13 +135,19 @@ protected override DateTime GetIndexDate(string index)
...
     }
 
-    private readonly Dictionary<DateTime, object> _ensuredDates = new();
     protected async Task EnsureDateIndexAsync(DateTime utcDate)
     {
         utcDate = utcDate.Date;
         if (_ensuredDates.ContainsKey(utcDate))
             return;
 
+        await using var indexLock = await _ensureIndexLock.AcquireAsync($"Index:{GetVersionedIndex(utcDate)}", TimeSpan.FromMinutes(1)).AnyContext();
```
Comment (niemyjski) [inline src/Foundatio.Repositories.Elasticsearch/Configuration/DailyIndex.cs:144]: It kind of feels like we should be locking on the index name here, but this allows us to go wide. I'm wondering if we should also change this to a concurrent dictionary.

File: src/Foundatio.Repositories.Elasticsearch/Configuration/DailyIndex.cs [hunk 4]
```diff
@@ -131,13 +135,19 @@ protected override DateTime GetIndexDate(string index)
...
+        if (indexLock is null)
+            throw new Exception("Unable to acquire index lock");
```
Comment (ejsmith) [inline src/Foundatio.Repositories.Elasticsearch/Configuration/DailyIndex.cs:146]: We should check to see if another process created the index we are looking for instead of just throwing here.

**Review by ejsmith — APPROVED** [review]
I like this change. Should be good.

**Review by ejsmith — CHANGES_REQUESTED** [review]
Actually, just thought about something. DailyIndex should be a singleton. Couldn't we just change the _ensuredDates to be a concurrent dictionary and not do a distributed lock?

**Comment by niemyjski** [comment]
@ejsmith I thought about that, we probably could. That's making assumptions it is registered as a singleton and then there is alias management going on. Seems safer to do it like this.

**Comment by ejsmith** [comment]
There would actually be a single instance per daily index and we can count on that because that's how it has to be registered for a daily index to work. So I think just changing to a concurrent dictionary would work and is what we want to do.

**Comment by ejsmith** [comment]
There are just multiple threads trying to ensure an index for a specific day at the same time. Which is what the error you are seeing is from.

**Review by ejsmith — COMMENTED** [review]
Looks good
